import 'server-only';

import { logger } from '@/lib/logger';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { toBusinessDate, type BusinessDate } from '@/lib/domain/datetime';
import { toUgx, type UgxAmount } from '@/lib/domain/money';
import {
  assertScheduleInvariants,
  type RepaymentSchedule,
  type ScheduledInstallment,
  type SchedulePeriodInput,
} from '@/lib/domain/repayment-schedule';
import { getLoanPeriods } from '@/lib/data/loans';

/**
 * Reading repayment schedules.
 *
 * Every query runs as the signed-in caller, so Row Level Security decides what
 * comes back. Nothing here uses the privileged client.
 *
 * ## There is no write function in this module
 *
 * Deliberately. A schedule is generated by `public.generate_loan_schedule`
 * inside the disbursement transaction, and that function is not granted to
 * `authenticated` at all — there is no path from the application to writing a
 * collection plan, so there is no function here that could be called by
 * mistake. Disbursement already produces the schedule; see
 * `lib/loans/actions.ts`.
 */

export interface LoanInstallment {
  readonly id: string;
  readonly installmentNumber: number;
  readonly loanPeriodNumber: number;
  readonly periodInstallmentNumber: number;
  readonly dueDate: BusinessDate;
  readonly scheduledPrincipal: UgxAmount;
  readonly scheduledInterest: UgxAmount;
  readonly expectedAmount: UgxAmount;
}

export interface LoanScheduleHeader {
  readonly loanId: string;
  readonly repaymentFrequency: string;
  readonly frequencyLabel: string;
  readonly intervalDays: number;
  readonly disbursementDate: BusinessDate;
  readonly businessTimezone: string;
  readonly generatorVersion: number;
  readonly generatedAt: string;
}

/**
 * A loan's schedule with the totals a screen needs.
 *
 * Every total is summed **from the installment rows** rather than stored, so
 * it cannot disagree with them. `reconciles` reports whether the rows add up
 * to the contractual total, which the interface uses to refuse to present
 * figures it cannot stand behind.
 */
export interface LoanScheduleView {
  readonly header: LoanScheduleHeader;
  readonly installments: readonly LoanInstallment[];
  readonly installmentCount: number;
  readonly firstDueDate: BusinessDate;
  /** The last collection date — the loan's scheduled completion date. */
  readonly finalDueDate: BusinessDate;
  readonly totalScheduledPrincipal: UgxAmount;
  readonly totalScheduledInterest: UgxAmount;
  readonly totalScheduledAmount: UgxAmount;
  /** Do the rows sum to the loan's contractual total? */
  readonly reconciles: boolean;
}

export async function getLoanScheduleHeader(
  loanId: string,
): Promise<LoanScheduleHeader | null> {
  const supabase = await createSupabaseServerClient();

  const { data, error } = await supabase
    .from('loan_schedules')
    .select(
      'loan_id, repayment_frequency, frequency_label, interval_days, disbursement_date, business_timezone, generator_version, generated_at',
    )
    .eq('loan_id', loanId)
    .maybeSingle();

  if (error !== null || data === null) {
    if (error !== null) {
      logger.warn('Could not read a loan schedule.', { code: error.code });
    }
    return null;
  }

  return {
    loanId: String(data.loan_id),
    repaymentFrequency: String(data.repayment_frequency),
    frequencyLabel: String(data.frequency_label),
    intervalDays: Number(data.interval_days),
    disbursementDate: toBusinessDate(String(data.disbursement_date)),
    businessTimezone: String(data.business_timezone),
    generatorVersion: Number(data.generator_version),
    generatedAt: String(data.generated_at),
  };
}

export async function getLoanInstallments(
  loanId: string,
): Promise<readonly LoanInstallment[]> {
  const supabase = await createSupabaseServerClient();

  const { data, error } = await supabase
    .from('loan_installments')
    .select(
      'id, installment_number, loan_period_number, period_installment_number, due_date, scheduled_principal, scheduled_interest, expected_amount',
    )
    .eq('loan_id', loanId)
    .order('installment_number', { ascending: true });

  if (error !== null) {
    logger.warn('Could not read loan installments.', { code: error.code });
    return [];
  }

  return (data ?? []).map((row) => ({
    id: String(row.id),
    installmentNumber: Number(row.installment_number),
    loanPeriodNumber: Number(row.loan_period_number),
    periodInstallmentNumber: Number(row.period_installment_number),
    dueDate: toBusinessDate(String(row.due_date)),
    scheduledPrincipal: toUgx(Number(row.scheduled_principal)),
    scheduledInterest: toUgx(Number(row.scheduled_interest)),
    expectedAmount: toUgx(Number(row.expected_amount)),
  }));
}

/**
 * The whole schedule for a loan, with its totals and a reconciliation verdict.
 *
 * Returns `null` when no schedule exists — which is the ordinary state of a
 * draft, a submitted or an approved loan, not an error. A schedule appears at
 * disbursement.
 */
export async function getLoanSchedule(
  loanId: string,
  contractualTotal?: number,
): Promise<LoanScheduleView | null> {
  const [header, installments] = await Promise.all([
    getLoanScheduleHeader(loanId),
    getLoanInstallments(loanId),
  ]);

  if (header === null) return null;

  const first = installments[0];
  const last = installments.at(-1);

  // A header with no installments cannot happen — they are written in one
  // transaction and both tables are append-only — but reading it as a schedule
  // would mean inventing a first and final date, so it is reported as absent.
  if (first === undefined || last === undefined) {
    logger.warn('A loan schedule header exists with no installments.', { loanId });
    return null;
  }

  const totalScheduledPrincipal = toUgx(
    installments.reduce((total, row) => total + row.scheduledPrincipal, 0),
  );
  const totalScheduledInterest = toUgx(
    installments.reduce((total, row) => total + row.scheduledInterest, 0),
  );
  const totalScheduledAmount = toUgx(
    installments.reduce((total, row) => total + row.expectedAmount, 0),
  );

  return {
    header,
    installments,
    installmentCount: installments.length,
    firstDueDate: first.dueDate,
    finalDueDate: last.dueDate,
    totalScheduledPrincipal,
    totalScheduledInterest,
    totalScheduledAmount,
    // Compared against the contract when the caller supplies it. A schedule
    // that does not reconcile is a defect, and the interface says so rather
    // than presenting figures nobody can stand behind.
    reconciles:
      contractualTotal === undefined || totalScheduledAmount === contractualTotal,
  };
}

/**
 * Re-check a stored schedule against the contract it was generated from.
 *
 * The database reconciles before it commits, so this should never fail. It
 * exists because "should never fail" is an argument and this is money: a
 * corrupted schedule is caught at the point it is read rather than believed.
 * Returns the first invariant that failed, or `null`.
 */
export async function verifyStoredSchedule(loanId: string): Promise<string | null> {
  const [header, installments, periods] = await Promise.all([
    getLoanScheduleHeader(loanId),
    getLoanInstallments(loanId),
    getLoanPeriods(loanId),
  ]);

  if (header === null) return null;
  if (periods.length === 0)
    return 'The loan has no contractual breakdown to check against.';

  const first = installments[0];
  const last = installments.at(-1);

  if (first === undefined || last === undefined) {
    return 'The schedule has no collections.';
  }

  const rebuilt: RepaymentSchedule = {
    installments: installments.map((row): ScheduledInstallment => ({
      installmentNumber: row.installmentNumber,
      loanPeriodNumber: row.loanPeriodNumber,
      periodInstallmentNumber: row.periodInstallmentNumber,
      dueDate: row.dueDate,
      scheduledPrincipal: row.scheduledPrincipal,
      scheduledInterest: row.scheduledInterest,
      expectedAmount: row.expectedAmount,
    })),
    windows: [],
    disbursementDate: header.disbursementDate,
    intervalDays: header.intervalDays,
    firstDueDate: first.dueDate,
    finalDueDate: last.dueDate,
    totalScheduledPrincipal: toUgx(
      installments.reduce((total, row) => total + row.scheduledPrincipal, 0),
    ),
    totalScheduledInterest: toUgx(
      installments.reduce((total, row) => total + row.scheduledInterest, 0),
    ),
    totalScheduledAmount: toUgx(
      installments.reduce((total, row) => total + row.expectedAmount, 0),
    ),
  };

  const contractual: readonly SchedulePeriodInput[] = periods.map((period) => ({
    periodNumber: period.periodNumber,
    principalPortion: period.principalPortion,
    interest: period.interest,
    totalObligation: period.totalObligation,
  }));

  try {
    assertScheduleInvariants(rebuilt, contractual);
    return null;
  } catch (error) {
    return error instanceof Error ? error.message : 'The stored schedule is invalid.';
  }
}
