-- ===========================================================================
-- Phase 5 — schedule capabilities.
--
-- ## One capability, and why not two
--
-- The obvious shape is `schedules:view` plus `schedules:view_all`. It was not
-- built, because in this business the two would be the same capability under
-- two names.
--
-- A repayment schedule is visible exactly when its loan is. Every staff role
-- that reads schedules — Secretary/Treasurer, Manager, Owner — already holds
-- `loans:view`, which is the whole register; there is no role that sees some
-- loans and not others. So `schedules:view_all` would grant precisely what
-- `schedules:view` already grants, and a capability that cannot be
-- distinguished from another is a false promise about what the system
-- enforces. Phase 4 made the same call about statuses nothing could set.
--
-- If the business later introduces a branch or officer scoping where one
-- person genuinely sees a subset of loans, the distinction becomes real and
-- the capability can be added then — with the policy that makes it mean
-- something.
--
-- ## No create, edit or delete capability, deliberately
--
-- There is no `schedules:create`, `schedules:edit` or `schedules:delete`. The
-- schedule is generated by the database inside the disbursement transaction
-- and is then contractual history. No role may write one by hand, so no
-- capability exists to be granted by mistake — the same reasoning that kept a
-- DELETE grant out of Phase 4 entirely.
--
-- Rescheduling and restructuring are a later, explicitly audited workflow if
-- the business wants them. They are not an "edit schedule" button.
-- ===========================================================================

insert into public.permissions (key, description)
values
  ('schedules:view', 'See the repayment collection schedule generated for a loan.')
on conflict (key) do update set description = excluded.description;

insert into public.role_permissions (role_key, permission_key)
values
  -- The Secretary/Treasurer collects the money, so the schedule is the
  -- document they work from daily.
  ('secretary_treasurer', 'schedules:view'),
  ('manager', 'schedules:view'),
  ('owner_admin', 'schedules:view')
  -- `client` holds nothing. A borrower reads their own schedule through the
  -- ownership clause in the Row Level Security policy, not through a
  -- capability — matching how Phase 4 prepared borrower access to loans.
on conflict (role_key, permission_key) do nothing;
